### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by plegrand1** [hellzerg/mint#1]
Jotti, VirusTotal and windows defender detect virus
![image](https://user-images.githubusercontent.com/8543044/169465406-6b7f8696-83cf-4ffe-86fc-152b24004e87.png)
![image](https://user-images.githubusercontent.com/8543044/169465479-a1b57d4e-4251-4145-a8be-6c28169b9c6e.png)

**Comment by lifeowner** [comment]
That's a false positive, please make sure you download the tool from official release github, which is : https://github.com/hellzerg/mint/releases/download/1.7/Mint-1.7.exe , however it might found as a virus cause it injects explorer or process from windows which malicious software does too, but in fact as you well know it's open source, which you may see as well the source and edit this for yourself. So in short words, there's nothing we can do regarding anti virus software, they are false positive 99% of the time, that's because they find any access to the system as a thread.
